version: 2
updates:
  # 1. Monitor GitHub Actions updates to prevent CI and CodeQL deprecation
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # 2. Monitor base image updates in the Dockerfile
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
