services:
  mona_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER:-mona_dev}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]    
    image: mona_robot:humble
    container_name: mona_dev
    
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ALSOFT_DRIVERS=null
    
    volumes:
      - ./src:/home/${USER:-mona_dev}/mona_ws/src
      - ./scripts:/home/${USER:-mona_dev}/mona_ws/scripts
      - ./configs:/home/${USER:-mona_dev}/mona_ws/configs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/${USER:-mona_dev}/.Xauthority:rw

    command: sleep infinity
    tty: true
    stdin_open: true
