name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Сборка образа
      - name: Build Docker Image
        run: |
          docker build . \
            --file Dockerfile \
            --tag mona_ci \
            --build-arg USER_UID=1001 \
            --build-arg USER_GID=1001

      # 2. Запуск скрипта local_ci.bash
      # Мы монтируем папки src и scripts точно так же, как в docker-compose
      # Это гарантирует, что тестируется именно тот код, который запушен.
      - name: Run Global CI Script inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/src:/home/mona_dev/mona_ws/src \
            -v ${{ github.workspace }}/scripts:/home/mona_dev/mona_ws/scripts \
            mona_ci \
            /bin/bash -c "cd /home/mona_dev/mona_ws && ./src/scripts/local_ci.bash"