name: CI

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  schedule:
    - cron: '0 2 * * 1'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # 1. Настройка Buildx (нужен для кэша)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Сборка образа через Buildx с кэшированием
      - name: Build Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
          tags: mona_ci:latest
          # Выгружаем образ в обычный Docker демон, 
          # чтобы следующий шаг (docker run) его увидел
          load: true
          build-args: |
            USER_UID=1001
            USER_GID=1001
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: ${{ github.event_name == 'schedule' }}

      # 3. Монтируем папки src и scripts, чтобы тестировать свежий код
      - name: Run Global CI Script inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/src:/home/mona_dev/mona_ws/src \
            -v ${{ github.workspace }}/scripts:/home/mona_dev/mona_ws/scripts \
            -v ${{ github.workspace }}/configs:/home/mona_dev/mona_ws/configs \
            mona_ci:latest \
            /bin/bash -c "cd /home/mona_dev/mona_ws && ./scripts/local_ci.bash"
