name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Настройка Buildx (нужен для продвинутого кэширования)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. Сборка образа с использованием кэша GitHub Actions
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: mona_ci:latest
          # ВАЖНО: load: true выгружает образ из Buildx в обычный Docker,
          # чтобы мы могли запустить его в следующем шаге
          load: true
          build-args: |
            USER_UID=1001
            USER_GID=1001
          # Магия кэширования:
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 3. Тестирование сборки кода внутри контейнера
      - name: Build Workspace (Colcon)
        run: |
          docker run --rm mona_ci:latest \
            /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build"